### ISSUE TITLE
Git should ignore generated files

### ISSUE THREAD

**Issue by agilarity** [mukatee/osmo#44]
Git should ignore files generated by Maven, common IDEs, and the OS to make it easier to make contributions. I noticed the project does not have a git ignore file.

I will be happy to create one and submit a pull request.

Are you open to contributions?

**Comment by mukatee** [comment]
Hi,

 Sorry for the loong delays, obviously I don't seem to have configured my account to get notifications properly. Will try to fix that. 

 If you have an ignore file or any other useful commits, I would be happy to receive them.

Cheers

**Comment by mukatee** [comment]
closing with the provided .gitignore merged
