### ISSUE TITLE
WriterLoaderTests.writeAndLoadTwoTests fails on Ubuntu

### ISSUE THREAD

**Issue by agilarity** [mukatee/osmo#53]
I get this failure when running on Ubuntu 14.04 LTS. It does not fail on Windows 10.

WriterLoaderTests.writeAndLoadTwoTests:79 Scripts expected:<[TestScript{seed=[5555555555, steps=[login, send message, logout]}, TestScript{seed=-99, steps=[tweet, tweet, insta, cave]]}]> but was:<[TestScript{seed=[-99, steps=[tweet, tweet, insta, cave]}, TestScript{seed=5555555555, steps=[login, send message, logout]]}]>

The root cause is that the test assumes the order of the expected result strings.

The test should check that the expected TestScript objects are equal to the actual set.

Here is the new scenario.
```
Given some test cases with steps
When the scripts are written for each test case
Then the test script data will match the test case
```

I will submit a pull request to fix this and the other Ubuntu failure I raised, #52.

**Comment by mukatee** [comment]
Thanks for the reports. It seems the simplest fix could be to just sort the list and assert on that. But is there some simple way to write the type of assert you refer to in AssertJ? This generic assert type often comes up. Was trying out AssertJ on the reducertest but not sure on the best ways to apply it.

**Comment by mukatee** [comment]
These should be fixed now since i just sorted the lists. let me know if you still have issues

**Comment by agilarity** [comment]
Yes, sorting the list will address the cause of this failure. However, there is a more general problem at work here. The `toString()` method is meant to produce an informative message about an object. It is not designed for comparing objects. So, it would be better to compare `TestScript` collections instead of the `toString()` methods. This would make it possible to say something like `assertThat(scripts).containsAll(expectedTestScripts);`

Assertion frameworks like AssertJ depend on object equality. I recommend implementing `hashcode()` and `equals()` on data objects, with the help of the Java `Objects` class. The cost of the change will reward you code that is easier to test. I also recommend testing equality with the [Equals Verifier](https://github.com/jqno/equalsverifier) because it can be tricky.

I will be happy to add equality support to  `TestScript` if you decide it is a good idea. I am also willing to refactor `WriterLoaderTests` to compare objects instead of `toString()' methods.
